### PR TITLE
build0020: Bundle db4o, upload WoT JAR from Travis CI to Freenet

### PR DESCRIPTION
**Pull request by xor-freenet**
### Test results

This build has been posted to FMS on ```2018-06-01```.  
There have been no bug reports.

A measurement of yesterday, ```2018-07-10```, shows these numbers of identities using the given builds:
```
[...]
    890 <WebOfTrust Version="19">
     11 <WebOfTrust Version="20">
```

Travis CI ran the unit tests every day since ```2018-06-01``` against fred branch ```next```.  
There was only one failure, and it was unrelated to WoT, it was caused by networking issues at Travis.

### Review instructions

To help you with your preference of not having to read very many commits during review my goal of a few months has been to write code which is more self-explanatory without reading the commit messages :)  
Thus feel free to review this and future PRs as a diff only. If any questions arise add them as a line comment, I'll be happy to answer them and document the source code if necessary.

For this PR I would recommend you to interpret "as a diff" as "as a diff for each branch" to ease review of individual features.
To see a branch diff:
```bash
gitk # Determine MERGE_COMMIT_HASH
git diff MERGE_COMMIT_HASH~1..MERGE_COMMIT_HASH
# or:
git difftool -t TOOL ...
```

Further, to reap something positive from the separation of the core team and me, I would suggest you and me also take a break from potential lengthy discussions and offer you the following idea:  
Review this and upcoming PRs _only_ for bugs and security issues and ignore anything else such as style or design decisions.  
I usually review my commits at least thrice for code quality, so rest assured it is being dealt with.
Btw.: Please submit security issues by encrypted email, not here.

The changelog is in tag ```build0020``` and [here](https://github.com/xor-freenet/plugin-WebOfTrust/blob/9295f39ac70ba10b68f55024f03ce6327d5775ce/developer-documentation/changelogs/build0020.txt), I'd recommend reading it before reviewing.

### Merge instructions

This should be merged **without** a merge-commit as shown below to ensure the ```HEAD``` commit of ```freenet/master``` matches the signed tag ```build0020``` which I've pushed.  
That is necessary for fred to display the version of the WoT plugin properly.

```bash
cd plugin-WebOfTrust
git remote add xor https://github.com/xor-freenet/plugin-WebOfTrust.git
git fetch xor
git checkout master
git diff HEAD..xor/master # Review
git merge --ff-only xor/master
git push --follow-tags origin master # --follow-tags = push the "build0020" tag
git push --follow-tags freenet master
```

### Important post-merge stuff

As the changelog describes in detail this build uses your nice pyFreenet features to make Travis CI upload the JAR to Freenet :)  
Travis CI runs on ```master``` as a cronjob every day on my repository so there's always a fresh CHK available [in the daily build log](https://travis-ci.org/xor-freenet/plugin-WebOfTrust/builds). Thus you should make up your mind on whether you want to use that JAR in Freenet releases, or keep compiling WoT on your own.  
Arguably the weakest link in the security chain of that is probably whether the ```pip3``` stuff which you recommend to obtain pyFreenet is secure.  
To make it robust against that being hacked I can make the next WoT build ```git clone``` a specific commit of pyFreenet instead if you tell me which branch of which repository is equal to what's on ```pip3```.

If you do want to keep compiling WoT on your own, I would be grateful if you could test whether my changes to the Ant builder which make it download the db4o source code do work in your release environment.  
What would especially make me very happy is if you could do this soon-ish so there is enough time left for me to fix issues with it before the next fred release.

Finally, please consider posting the changelog to devl after merging :) It has email-compatible formatting.  
I do get devl mails but have received no instructions about whether I'm allowed to post changelogs.

### CODE REVIEW

**Comment by ArneBab** [comment]
Looks good to me. Merging. Thank you!

**Comment by ArneBab** [comment]
Hi,

just a short update: 1482 is an emergency release with only small
changes compared to 1481. Nothing which should affect WoT.

Best wishes,
Arne

xor-freenet <notifications@github.com> writes:

> @ArneBab 
>> Testing on my release environment will still have to wait a few days, though.
>
> Now that fred build 1482 is in development (thanks for finishing 1481!), and this WoT build might have to be shipped with 1482 in order to allow removal of db4o from freenet-ext, can you please do test whether this WoT build here compiles and unit tests succeed in your release envrionment?
>
> Also for the sake of paranoia please have a look at the resulting WebOfTrust.jar with a zip software to see whether it does indeed contain the `com.db4o.*` classes.
>
> Doing this early will allow me to fix potential problems soon enough to not interfere with fred's roadmap.


-- 
Unpolitisch sein
heißt politisch sein
ohne es zu merken

**Comment by xor-freenet** [comment]
@ArneBab  wrote:
> just a short update: 1482 is an emergency release with only small changes compared to 1481.
> Nothing which should affect WoT.

Thanks! I wasn't referring to the emergency release but to the general roadmap which Steve told me about: that after the just finished 1481 the removal of db4o will happen. I suppose the emergency release won't change that.

**Comment by ArneBab** [comment]
I can build 9295f39ac70ba10b68f55024f03ce6327d5775ce

**Pull request merged**
